amix/vimrc

README.md
Excellent package! Some users reached out to me for help. Cheers.
=> Note to install ctags

.gitmodules
This PR proposes the great [git gutter](https://github.com/airblade/vim-gitgutter) plugin. Nothing to configure it just works.
=> Adds plugin vim-gitgutter

.gitmodules
There's already several themes in this vimrc, yet this one ( [gruvbox](https://github.com/morhetz/gruvbox) ) seems quite nice and well integrated. It is also inspired by the infamous solarized
=> Adds gruvbox as a submodule

vimrcs/basic.vim
I assume that this was an error?
=> en => endif

README.md
git is now replaced with https
=> updated repo link

README.md
Ctags updated installation (with Markdown for Debian/Ubuntu); added command for Arch Linux.
=> Ctags updated installation

vimrcs/basic.vim
Don't know if this was not enabled on purpose
=> Enable jumping to the last position in file on open

vimrcs/basic.vim
opinionated bindings though, but easy to use, enjoy!
=> key bindings for :bnext and :bprev

vimrcs/basic.vim
This is for the basic.vim configuration
=> Adding column number to status line

vimrcs/basic.vim
=> enable search with visual selection with highlight

.gitignore, temp_dirs/undodir/.gitignore
This patch aims to make the persistent undo functionality work out of
the place.
=> Create the empty undodir.

README.md
It seems that Adobe has migrated all their fonts to Typekit.
=> Update link to Source Code Pro by Adobe.

vimrcs/filetypes.vim
Signed-off-by: weiyang <weiyang.ones@gmail.com>
=> [tmux] set 'termguicolors' when running nvim

README.md
On the Opera browser's (http://www.opera.com/) speed dial, you can set images as "logo's" for a website. This image is a nice logo.
=> [major(?)] Added vim logo

README.md
Using git clone --depth=1 is much faster, as it doesnt clone the entire history of the repo.
=> Speed up download ~4x

README.md
site has changed to gitforwindows.org
=> change to new site

vimrcs/basic.vim
why? May be there's a reason anyway in case you missed it.
=> remove additional height

vimrcs/plugins_config.vim
The Lightline colorscheme setting was being set twice.
=> removed dupe Lightline setting

README.md
ALE requires NeoVim >= 0.2.0 or Vim 8 with +timers +job +channel.
=> ALE commands not working

sources_non_forked/rust.vim/LICENSE-APACHE, sources_non_forked/rust.vim/LICENSE-MIT, sources_non_forked/rust.vim/README.md, sources_non_forked/rust.vim/after/syntax/rust.vim, sources_non_forked/rust.vim/autoload/cargo.vim, sources_non_forked/rust.vim/autoload/rust.vim, sources_non_forked/rust.vim/autoload/rustfmt.vim, sources_non_forked/rust.vim/compiler/cargo.vim, sources_non_forked/rust.vim/compiler/rustc.vim, sources_non_forked/rust.vim/doc/rust.txt, sources_non_forked/rust.vim/ftplugin/rust.vim, sources_non_forked/rust.vim/indent/rust.vim, sources_non_forked/rust.vim/plugin/rust.vim, sources_non_forked/rust.vim/syntax/rust.vim, sources_non_forked/rust.vim/syntax_checkers/rust/cargo.vim, sources_non_forked/rust.vim/syntax_checkers/rust/rustc.vim, update_plugins.py
Let me know if I missed anything?
Thanks!
=> Update rust.vim from deprecated repo to rust-lang repo and add to update_plugins.py

vimrcs/plugins_config.vim
=> change to new fugitive syntax

install_awesome_parameterized.sh
`ls /home` may be a straightforward equivalent to get the list of users.
=> chore: make it straightforward

install_awesome_parameterized.sh
Tried to run the parameterized script and had a problem at the compare and at the substitutions.
=> Fix sh script

README.md
Added native way to install plugins in vim 8+ without any plugin manager
=> add native plugin install to README

README.md
tried the font, made my code look pretty good, but didn't magically make it nicer code sadly :-(
=> update README to be more accurate

vimrcs/basic.vim
Noticed typo that broke <leader>tl
=> Fix <leader>tl

vimrcs/basic.vim
=> Change Unicode dash in basic.vim#3 to ASCII one

update_plugins.py
=> add copilot

README.md
Closes https://github.com/amix/vimrc/issues/739.
Note I also added some [semantic line feeds](https://sembr.org/) to enable a cleaner `git diff` in the future
=> Clarifying `my_configs.vim` docs in `README`
