- vimrcs/extended.vim
found this in ```help:gfn```.
>For the GTK+ 2 GUI the font name looks like this: >
>    :set guifont=Andale\ Mono\ 11
> the font name setting for the GTK+ 2 GUI.

- update_plugins.py
Using Python 3's concurrent.futures to download plugin updates concurrently. In Python 2 one can use futures package as a backport of the concurrent.futures. If any of those packages is not found, plugins will be downloaded sequentially.
> Improve download speed of update plugin script

- README.md
- sources_non_forked/ctrlp.vim/.gitignore
- sources_non_forked/ctrlp.vim/autoload/ctrlp.vim
- sources_non_forked/ctrlp.vim/autoload/ctrlp/autoignore.vim
- sources_non_forked/ctrlp.vim/autoload/ctrlp/bookmarkdir.vim
- sources_non_forked/ctrlp.vim/autoload/ctrlp/buffertag.vim
- sources_non_forked/ctrlp.vim/autoload/ctrlp/mrufiles.vim
- sources_non_forked/ctrlp.vim/autoload/ctrlp/tag.vim
- sources_non_forked/ctrlp.vim/doc/ctrlp.cnx
- sources_non_forked/ctrlp.vim/doc/ctrlp.txt
- sources_non_forked/ctrlp.vim/plugin/ctrlp.vim
- sources_non_forked/ctrlp.vim/readme.md
- update_plugins.py
While I was reading the README file, I found this project still using unmaintained plugin [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim), they suggest switch to the [ctrlpvim/ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim), which is the current ctrlp.vim active development project.
Please review, thanks.
> Use ctrlpvim/ctrlp.vim instead of unmaintained kien/ctrlp.vim

- vimrcs/basic.vim
Current configuration was not disabling that annoying sounds on MacVim. According to help:
```
Use visual bell instead of beeping.  The terminal code to display the
visual bell is given with 't_vb'.  When no beep or flash is wanted,
use ":set vb t_vb=".
Note: When the GUI starts, 't_vb' is reset to its default value.  You
might want to set it again in your |gvimrc|.
```
> Properly disable sound on errors on MacVim

- vimrcs/plugins_config.vim
Save typing space when using <leader>nb
> Add training space to <leader>nb map of NERDTreeFromBookmark

- vimrcs/filetypes.vim
Hello,
First of all, congrats for this awesome configurations.
I usually work with Twig template engine, which is widely used in PHP and its frameworks (Symfony, Silex, etc.). As it's almost just HTML, I've considered a good idea to just set the same syntax defined for HTML.
Hope you find useful.
Best regards,
Julen
> Set HTML syntax for Twig files

- vimrcs/plugins_config.vim
Hi,
I wanted to move vim_runtime but the plugin folders were using absolute path. 
See here http://stackoverflow.com/a/18734557 more info on the path resolution.
Specifically, there is a warning about symlinks. I suppose it could be a problem.
> Make plugins_config use relative path

- vimrcs/basic.vim
Since we are already defining mapleader to ",", there is no need to define g:leader as well.
So I removed g:mapleader from the vimrc, to make it simpler.
> Removed let g:mapleader in line 59

- vimrcs/basic.vim
replaced `et.c` with `etc.` in line 166.
> fixed a spelling mistake in basic.vim

- vimrcs/extended.vim
Gui font config syntax  `name:size` only works on Windows & Mac, for gtk & linux (tested in archlinux) we need to use `name size` (a space between the font name & size).
> Fix guifont config format in gtk2 & linux, see also #436

- vimrcs/basic.vim
- Adds au FocusGained,BufEnter * checktime to actually trigger the
reload.
- set autoread on its own isnt enough.
> Fix autoreload file from external change.

- vimrcs/basic.vim
`source $MYVIMRC` will fail since command `W` exists.
Add `!` so the command would be redefined
> fix(basic.vim): change `command W` to `command! W`

- install_awesome_parameterized.sh
line 34 had `~/$user` which evaluates to `/home/user1/user1`. Now changed into `~$user` as above
> fix typo when installing for specific users

- vimrcs/plugins_config.vim
Fix the annoying error message about the SnipMate version 0 deprecation
```
$ vim foo
The legacy SnipMate parser is deprecated. Please see :h SnipMate-deprecate.
Press ENTER or type command to continue
```
With this commit, version 1 is now default.
> [snipMate] set to default version 1

- README.md
The following error occurs when calling `python update_plugins.py` on a fresh install of vimrc and python that does not yet have the `requests` module installed.
```
Traceback (most recent call last):
File "/Users/basti/.vim_runtime/update_plugins.py", line 12, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
```
The `requests` python module is not included by default and must be installed manually before `python update_plugins.py` will work properly.
> improve README instructions for installing updates

- update_plugins.py
original tlib repo is not maintained any more, new official repo has been transfered to github already, we should transfer to new official repo. This will also fix E1208 Error. #645 #647
> change tlib's repo address

- update_plugins.py
The original update_plugins.py should work fine, but if I use an accelerated domain name (like https://github.com.cnpmjs.org/), it will not automatically redirect to the new repo address. Therefore I updated the plugins repo to the new ones.
> plugin update change repo

- sources_forked/peaksea/colors/peaksea.vim
Spellcheck colors are disabled since v3.3 of `peaksea.vim`, see: https://www.vim.org/scripts/script.php?script_id=760. This commit restores the colors, thus fixing #418 & #548. See more explanations in https://github.com/amix/vimrc/issues/548#issuecomment-1207165114.
> Restore spellcheck colors, fix #418 & #548

- README.md
The mapping to remove highlighting was present in the wrong code block.
> Fix small Error

- README.md
- vimrcs/basic.vim
- vimrcs/extended.vim
I know, no one should use spaces in paths, but if anyone does this PR escapes them. 😉
> fix: escape spaces in expanded paths

- README.md
- vimrcs/plugins_config.vim
Make native packages easier to setup.
Tested on
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 15 2023 04:26:05)
macOS version - x86_64
Included patches: 1-1424
Compiled by root@apple.com
```
and
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
```
> Fix support for native vim packages

- vimrcs/basic.vim
Closes #729
Source: <https://morgan.cugerone.com/blog/troubleshooting-vim-error-while-processing-cursorhold-autocommands-in-command-line-window>
> Fix autocommand error when opening command line window

- README.md
Adds missing closing code fence in README.md to fix incorrect formatting of vim-snipmate mappings.
> Fix broken code block in README.md
